import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:sizer/sizer.dart';

// Import firebase_options (generated by flutterfire configure)
import 'firebase_options.dart';

// Import Providers
import 'admin/providers/auth_provider.dart';
import 'admin/providers/theme_provider.dart';
import 'admin/providers/product_provider.dart';
import 'admin/providers/category_provider.dart';
import 'admin/providers/order_provider.dart';
import 'admin/providers/sales_provider.dart';
import 'admin/providers/customer_provider.dart';
import 'admin/providers/expense_provider.dart';
import 'admin/providers/barcode_provider.dart';

// Import Screens
import 'admin/screens/auth/login_screen.dart';
import 'admin/screens/dashboard_screen.dart';

// Import Theme
import 'admin/theme/bareeq_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const BareeqAdminApp());
}

class BareeqAdminApp extends StatelessWidget {
  const BareeqAdminApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => SalesProvider()),
        ChangeNotifierProvider(create: (_) => ProductProvider()),
        ChangeNotifierProvider(create: (_) => CategoryProvider()),
        ChangeNotifierProvider(create: (_) => OrderProvider()),
        ChangeNotifierProvider(create: (_) => SalesProvider()),
        ChangeNotifierProvider(create: (_) => CustomerProvider()),
        ChangeNotifierProvider(create: (_) => ExpenseProvider()),
        ChangeNotifierProvider(create: (_) => BarcodeScannerProvider()),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, child) {
          return Sizer(
            builder: (context, orientation, deviceType) {
              return MaterialApp(
                title: 'Bareeq Admin - بريق',
                debugShowCheckedModeBanner: false,
                theme: getBareeqLightTheme(),
                darkTheme: getBareeqDarkTheme(),
                themeMode: themeProvider.themeMode,
                home: const AuthWrapper(),
                routes: {
                  '/login': (context) => const LoginScreen(),
                  '/dashboard': (context) => const DashboardScreen(),
                },
              );
            },
          );
        },
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (context, authProvider, child) {
        if (authProvider.isLoading) {
          return Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(
                    color: Theme.of(context).primaryColor,
                  ),
                  const SizedBox(height: 16),
                  Text(
                    'Loading...',
                    style: TextStyle(
                      color: Theme.of(context).primaryColor,
                      fontSize: 16,
                    ),
                  ),
                ],
              ),
            ),
          );
        }
        
        if (authProvider.isAuthenticated && authProvider.isAdmin) {
          return const DashboardScreen();
        }
        
        return const LoginScreen();
      },
    );
  }
}