import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:sizer/sizer.dart';

// Firebase options (generated by flutterfire configure)
import '../firebase_options.dart';

// Providers
import 'providers/auth_provider.dart';
import 'providers/theme_provider.dart';
import 'providers/product_provider.dart';
import 'providers/category_provider.dart';
import 'providers/order_provider.dart';
import 'providers/sales_provider.dart';
import 'providers/customer_provider.dart';
import 'providers/expense_provider.dart';
import 'providers/barcode_provider.dart';

// Screens
import 'screens/auth/login_screen.dart';
import 'screens/dashboard_screen.dart';

// Theme
import 'theme/bareeq_theme.dart';

/// =======================================================
/// ENTRY POINT FOR ADMIN APP
/// =======================================================
Future<void> runAdminApp() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const BareeqAdminApp());
}

/// =======================================================
/// ROOT APP
/// =======================================================
class BareeqAdminApp extends StatelessWidget {
  const BareeqAdminApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => ProductProvider()),
        ChangeNotifierProvider(create: (_) => CategoryProvider()),
        ChangeNotifierProvider(create: (_) => OrderProvider()),
        ChangeNotifierProvider(create: (_) => SalesProvider()),
        ChangeNotifierProvider(create: (_) => CustomerProvider()),
        ChangeNotifierProvider(create: (_) => ExpenseProvider()),
        ChangeNotifierProvider(create: (_) => BarcodeScannerProvider()),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, _) {
          return Sizer(
            builder: (context, orientation, deviceType) {
              return MaterialApp(
                title: 'Bareeq Admin - بريق',
                debugShowCheckedModeBanner: false,
                theme: getBareeqLightTheme(),
                darkTheme: getBareeqDarkTheme(),
                themeMode: themeProvider.themeMode,
                home: const AuthWrapper(),
                routes: {
                  '/login': (context) => const LoginScreen(),
                  '/dashboard': (context) => const DashboardScreen(),
                },
              );
            },
          );
        },
      ),
    );
  }
}

/// =======================================================
/// AUTH WRAPPER (NO FLICKER, NO RACE CONDITIONS)
/// =======================================================
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (context, authProvider, _) {

        // Wait for Firebase auth state to initialize
        if (!authProvider.isInitialized) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }

        // Show loading during sign-in / sign-out
        if (authProvider.isLoading) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }

        // Authenticated admin → dashboard
        if (authProvider.isAuthenticated && authProvider.isAdmin) {
          return const DashboardScreen();
        }

        // Otherwise → login
        return const LoginScreen();
      },
    );
  }
}